package goconfgen

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// // // // // // // // // //

const cGeneratedHeaderPrefix = "// Code generated by goconfgen; DO NOT EDIT."

func writeFileAtomically(targetPath string, dataArr []byte, force bool) error {
	dirPath := filepath.Dir(targetPath)
	targetInfoObj, err := os.Stat(targetPath)
	switch {
	case err == nil:
		if targetInfoObj.IsDir() {
			return fmt.Errorf("output file path is directory: %s", targetPath)
		}

		existingArr, readErr := os.ReadFile(targetPath)
		if readErr != nil {
			return fmt.Errorf("read output file: %w", readErr)
		}
		if bytes.Equal(existingArr, dataArr) {
			return nil
		}

		if !force {
			return fmt.Errorf("output file already exists: %s", targetPath)
		}
	case errors.Is(err, os.ErrNotExist):
	default:
		return fmt.Errorf("stat output file: %w", err)
	}

	fileObj, err := os.CreateTemp(dirPath, ".goconfgen-*.tmp")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}

	tempPath := fileObj.Name()
	defer func() {
		_ = os.Remove(tempPath)
	}()

	if _, err = fileObj.Write(dataArr); err != nil {
		_ = fileObj.Close()
		return fmt.Errorf("write temp file: %w", err)
	}

	if err = fileObj.Close(); err != nil {
		return fmt.Errorf("close temp file: %w", err)
	}

	if err = os.Rename(tempPath, targetPath); err != nil {
		return fmt.Errorf("replace output file: %w", err)
	}

	return nil
}

func prepareOutputDir(outputDir string, force bool) error {
	infoObj, err := os.Stat(outputDir)
	switch {
	case err == nil:
		if !infoObj.IsDir() {
			return fmt.Errorf("output path is not directory: %s", outputDir)
		}
		return nil
	case errors.Is(err, os.ErrNotExist):
		if !force {
			return fmt.Errorf("output directory does not exist: %s", outputDir)
		}
		if mkdirErr := os.MkdirAll(outputDir, 0o755); mkdirErr != nil {
			return fmt.Errorf("create output directory: %w", mkdirErr)
		}
		return nil
	default:
		return fmt.Errorf("stat output directory: %w", err)
	}
}

// cleanupStaleGeneratedFiles удаляет .go-файлы с нашим заголовком, которых нет в новом
// наборе. Чужие файлы и файлы без заголовка не трогаются. Имена не хардкодятся — стойко к
// переименованиям шаблонов.
func cleanupStaleGeneratedFiles(outputDir string, keepNameMap map[string]struct{}, force bool) error {
	entryObjArr, err := os.ReadDir(outputDir)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return fmt.Errorf("read output directory: %w", err)
	}

	staleNameArr := make([]string, 0)
	for _, entryObj := range entryObjArr {
		if entryObj.IsDir() {
			continue
		}

		nameText := entryObj.Name()
		if !strings.HasSuffix(nameText, ".go") {
			continue
		}
		if _, keepFlag := keepNameMap[nameText]; keepFlag {
			continue
		}

		pathText := filepath.Join(outputDir, nameText)
		generatedFlag, headerErr := hasGeneratedHeader(pathText)
		if headerErr != nil {
			return fmt.Errorf("read stale generated file [%s]: %w", nameText, headerErr)
		}
		if !generatedFlag {
			continue
		}

		if !force {
			staleNameArr = append(staleNameArr, nameText)
			continue
		}
		if err = os.Remove(pathText); err != nil {
			return fmt.Errorf("remove stale generated file [%s]: %w", nameText, err)
		}
	}

	if len(staleNameArr) > 0 {
		sort.Strings(staleNameArr)
		return fmt.Errorf("stale generated files would be removed with force: %v", staleNameArr)
	}
	return nil
}

// hasGeneratedHeader читает только префикс файла, не загружая его целиком.
func hasGeneratedHeader(pathText string) (bool, error) {
	fileObj, err := os.Open(pathText)
	if err != nil {
		return false, err
	}
	defer func() {
		_ = fileObj.Close()
	}()

	bufferArr := make([]byte, len(cGeneratedHeaderPrefix))
	readCount, err := io.ReadFull(fileObj, bufferArr)
	if err != nil && !errors.Is(err, io.ErrUnexpectedEOF) && !errors.Is(err, io.EOF) {
		return false, err
	}

	return bytes.Equal(bufferArr[:readCount], []byte(cGeneratedHeaderPrefix)), nil
}
