package goconfgen

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// // // // // // // // // //

func writeFileAtomically(targetPath string, dataArr []byte, force bool) error {
	dirPath := filepath.Dir(targetPath)
	targetInfoObj, err := os.Stat(targetPath)
	switch {
	case err == nil:
		if targetInfoObj.IsDir() {
			return fmt.Errorf("output file path is directory: %s", targetPath)
		}

		if !force {
			return fmt.Errorf("output file already exists: %s", targetPath)
		}
	case errors.Is(err, os.ErrNotExist):
	default:
		return fmt.Errorf("stat output file: %w", err)
	}

	fileObj, err := os.CreateTemp(dirPath, ".goconfgen-*.tmp")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}

	tempPath := fileObj.Name()
	defer func() {
		_ = os.Remove(tempPath)
	}()

	if _, err = fileObj.Write(dataArr); err != nil {
		_ = fileObj.Close()
		return fmt.Errorf("write temp file: %w", err)
	}

	if err = fileObj.Close(); err != nil {
		return fmt.Errorf("close temp file: %w", err)
	}

	if err = os.Rename(tempPath, targetPath); err != nil {
		return fmt.Errorf("replace output file: %w", err)
	}

	return nil
}

func prepareOutputDir(outputDir string, force bool) error {
	infoObj, err := os.Stat(outputDir)
	switch {
	case err == nil:
		if !infoObj.IsDir() {
			return fmt.Errorf("output path is not directory: %s", outputDir)
		}
		return nil
	case errors.Is(err, os.ErrNotExist):
		if !force {
			return fmt.Errorf("output directory does not exist: %s", outputDir)
		}
		if mkdirErr := os.MkdirAll(outputDir, 0o755); mkdirErr != nil {
			return fmt.Errorf("create output directory: %w", mkdirErr)
		}
		return nil
	default:
		return fmt.Errorf("stat output directory: %w", err)
	}
}

func cleanupStaleGeneratedFiles(outputDir string, keepNameMap map[string]struct{}, knownNameArr []string, force bool) error {
	if !force {
		return nil
	}
	for _, nameText := range knownNameArr {
		if _, keepFlag := keepNameMap[nameText]; keepFlag {
			continue
		}
		pathText := filepath.Join(outputDir, nameText)
		dataArr, err := os.ReadFile(pathText)
		switch {
		case errors.Is(err, os.ErrNotExist):
			continue
		case err != nil:
			return fmt.Errorf("read stale generated file [%s]: %w", nameText, err)
		}
		if !bytes.HasPrefix(dataArr, []byte("// Code generated by goconfgen; DO NOT EDIT.")) {
			continue
		}
		if err = os.Remove(pathText); err != nil {
			return fmt.Errorf("remove stale generated file [%s]: %w", nameText, err)
		}
	}
	return nil
}
