package codegen

import (
	"fmt"
	"go/format"
	"time"

	"github.com/amazing-generators/goconfgen/internal/ir"
)

// // // // // // // // // //

// //

func Build(packageObj *ir.PackageObj) ([]FileObj, error) {
	templateDataObj, err := buildTemplateData(packageObj)
	if err != nil {
		return nil, err
	}

	fileNameTextArr := GeneratedFileNameArr(packageObj)
	schemaLabelText := packageObj.SchemaLabel
	if schemaLabelText == "" {
		schemaLabelText = packageObj.SchemaPath
	}

	fileObjArr := make([]FileObj, 0, len(fileNameTextArr))
	for _, fileNameText := range fileNameTextArr {
		dataArr, renderErr := renderTemplateFile(fileNameText, templateDataObj)
		if renderErr != nil {
			return nil, fmt.Errorf("render generated file [%s]: %w", fileNameText, renderErr)
		}

		formattedArr, formatErr := format.Source(dataArr)
		if formatErr != nil {
			return nil, fmt.Errorf("format generated file [%s]: %w", fileNameText, formatErr)
		}

		fileObjArr = append(fileObjArr, FileObj{
			RelativePath: fileNameText,
			DataArr:      prependGeneratedHeader(formattedArr, schemaLabelText),
		})
	}

	return fileObjArr, nil
}

func prependGeneratedHeader(dataArr []byte, schemaPathText string) []byte {
	headerText := buildGeneratedHeader(schemaPathText)
	resultArr := make([]byte, 0, len(headerText)+len(dataArr))
	resultArr = append(resultArr, headerText...)
	resultArr = append(resultArr, dataArr...)
	return resultArr
}

func buildGeneratedHeader(schemaPathText string) string {
	return fmt.Sprintf(
		"// Code generated by goconfgen; DO NOT EDIT.\n// Generated at: %s\n// Source schema: %s\n\n",
		time.Now().Format(time.RFC3339),
		schemaPathText,
	)
}

func GeneratedFileNameArr(packageObj *ir.PackageObj) []string {
	resultArr := make([]string, 0, len(cFileSpecArr))
	for _, specObj := range cFileSpecArr {
		if specObj.Predicate(packageObj) {
			resultArr = append(resultArr, specObj.NameText)
		}
	}
	return resultArr
}

func KnownGeneratedFileNameArr() []string {
	resultArr := make([]string, 0, len(cFileSpecArr)+2)
	for _, specObj := range cFileSpecArr {
		resultArr = append(resultArr, specObj.NameText)
	}
	resultArr = append(resultArr, "parse_gen.go", "render_gen.go")
	return resultArr
}

type fileSpecObj struct {
	NameText  string
	Predicate func(*ir.PackageObj) bool
}

var cFileSpecArr = []fileSpecObj{
	{"types_gen.go", alwaysFile},
	{"enums_gen.go", func(packageObj *ir.PackageObj) bool { return len(packageObj.EnumObjArr) > 0 }},
	{"schema_gen.go", alwaysFile},
	{"field_meta_gen.go", alwaysFile},
	{"runtime_gen.go", alwaysFile},
	{"accessors_gen.go", alwaysFile},
	{"validate_gen.go", func(packageObj *ir.PackageObj) bool { return packageObj.HasValidate }},
	{"flags_gen.go", func(packageObj *ir.PackageObj) bool { return packageObj.HasCLI }},
	{"presets_gen.go", func(packageObj *ir.PackageObj) bool { return packageObj.HasPresets }},
	{"parsers_gen.go", alwaysFile},
	{"parser_yaml_gen.go", func(packageObj *ir.PackageObj) bool { return packageObj.HasYAML }},
	{"parser_json_gen.go", func(packageObj *ir.PackageObj) bool { return packageObj.HasJSON }},
	{"parser_hjson_gen.go", func(packageObj *ir.PackageObj) bool { return packageObj.HasHJSON }},
	{"parser_cli_gen.go", func(packageObj *ir.PackageObj) bool { return packageObj.HasCLI }},
}

func alwaysFile(packageObj *ir.PackageObj) bool {
	return true
}

func buildTemplateData(packageObj *ir.PackageObj) (*TemplateDataObj, error) {
	var presetObjArr []PresetTemplateObj
	var presetDataArr []byte
	if packageObj.HasPresets {
		var err error
		presetObjArr, presetDataArr, err = buildPresetBundle(packageObj)
		if err != nil {
			return nil, err
		}
	}

	return &TemplateDataObj{
		PackageName:            packageObj.PackageName,
		RootObj:                packageObj.RootObj,
		FieldObjArr:            packageObj.FieldObjArr,
		EnumObjArr:             packageObj.EnumObjArr,
		HasYAML:                packageObj.HasYAML,
		HasJSON:                packageObj.HasJSON,
		HasHJSON:               packageObj.HasHJSON,
		HasCLI:                 packageObj.HasCLI,
		HasValidate:            packageObj.HasValidate,
		HasRender:              packageObj.HasRender,
		HasPresets:             packageObj.HasPresets,
		HasInterfaces:          packageObj.HasInterfaces,
		HasSize:                packageObj.HasSize,
		HasDuration:            packageObj.HasDuration,
		HasMapAny:              packageObj.HasMapAny,
		HasTextSlice:           packageObj.HasTextSlice,
		PrimaryFormatTitle:     packageObj.PrimaryFormat,
		TypeImportTextArr:      collectTypeImports(packageObj),
		AccessorImportTextArr:  collectAccessorImports(packageObj),
		FieldMetaImportTextArr: collectFieldMetaImports(packageObj),
		RuntimeImportTextArr:   collectRuntimeImports(packageObj),
		FlagImportTextArr:      collectFlagImports(packageObj),
		ValidateImportTextArr:  collectValidateImports(packageObj),
		PresetImportTextArr:    collectPresetImports(packageObj),
		PresetObjArr:           presetObjArr,
		PresetDataArr:          presetDataArr,
	}, nil
}

func buildPresetBundle(packageObj *ir.PackageObj) ([]PresetTemplateObj, []byte, error) {
	rawDataArr := make([]byte, 0, 4096)
	resultArr := make([]PresetTemplateObj, 0, 3)

	appendSlice := func(dataArr []byte) (int, int) {
		startVal := len(rawDataArr)
		rawDataArr = append(rawDataArr, dataArr...)
		return startVal, len(dataArr)
	}

	for _, presetObj := range []ir.PresetObj{packageObj.FullPresetObj, packageObj.MinimalPresetObj, packageObj.MediumPresetObj} {
		itemObj := PresetTemplateObj{
			TitleText:      goName(presetObj.NameText),
			NameText:       presetObj.NameText,
			SourcePathText: presetObj.SourcePathText,
			PresentFlag:    presetObj.PresentFlag,
			FullFlag:       presetObj.GeneratedFromDefaults,
		}

		if presetObj.PresentFlag {
			itemObj.YAMLStart, itemObj.YAMLLen = appendSlice([]byte(presetObj.YAMLText))
			itemObj.JSONStart, itemObj.JSONLen = appendSlice([]byte(presetObj.JSONText))
			itemObj.HJSONStart, itemObj.HJSONLen = appendSlice([]byte(presetObj.HJSONText))
		}

		resultArr = append(resultArr, itemObj)
	}

	return resultArr, rawDataArr, nil
}
